- name: install nodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: NodeJS

- name: App setup and install dependencies
  ansible.builtin.import_role:
    name: common 
    tasks_from: user-app-dependencies

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Schema Set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: schema-setup

- name: enable and restarted
  ansible.builtin.import_role:
    name: common
    tasks_from: daemon-setup



