- name: install NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: NodeJS

- name: check user roboshop exits and  app directory exits
  ansible.builtin.import_role:
    name: common
    tasks_from: user-app-dependencies

- name: copy the catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: system daemon-reload
  ansible.builtin.import_role:
    name: common
    tasks_from: daemon-reload

- name: enable and start
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: true

- name: copy mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

