- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: enable and statrt nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: remove the file
  ansible.builtin.shell: rm -rf /usr/share/nginx/html/*

  - name: unzip or extract artifact
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes