- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: start the nginx
  ansible.builtin.service:
    name: nginx
    state: started  

- name: remove the Remove the default content that web server is serving.
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
    
- name: download web artifact
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: unzip or extract artifact
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy the configuration
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf 

- name: enable and restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted