- name: Installing nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: unzip or extract artifact
  ansible.builtin.unarchive:
    src: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy the roboshop.conf
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Enable and start nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started