- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove the Remove the default content that web server is serving.
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp/web.zip
    remote_src: yes

- name: copy the configuration
  ansible.bi=uiltin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf 

- name: enable and restart nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: restarted